AWSTemplateFormatVersion: '2010-09-09'
Description: Simple CloudFormation template to create a t2.micro EC2 instance with a Hello World webpage.

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-06b21ccaeff8cd686
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd
          sudo echo "<html><h1>Orange cohort set up their first Github Action!!</h1></html>" > /var/www/html/index.html

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP access only
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  WebsiteURL:
    Description: URL of the Hello World webpage
    Value: !Sub "http://${EC2Instance.PublicDnsName}"